apiVersion: v1 # Version der API
kind: Service # Service Objekttyp
metadata:
  labels:
    service: mariadb # Name des Service 
  name: mariadb # Name
spec:
  ports: # Angabe der verwendeten Ports
    - name: "http" # Name des Ports im Service
      port: 3306 
      targetPort: 3306
  selector:
    service: mariadb # Name des Service
