apiVersion: v1
kind: Service
metadata:
  labels:
    service: mariadb
  name: mariadb
spec:
  ports:
    - name: "http"
      port: 3306
      targetPort: 3306
  selector:
    service: mariadb
status:
  loadBalancer: {}
