apiVersion: v1 # Version der API
kind: ConfigMap # Angabe des Objekttyps
data: # Angabe der Umgebungsvariablen duer die Nextcloud
  NEXTCLOUD_ADMIN_PASSWORD: nextcloud-admin-password # Das Admin Passwort
  NEXTCLOUD_ADMIN_USER: admin # Admin Benutzername
  NEXTCLOUD_TRUSTED_DOMAINS: '192.168.49.2' # Minikube IP, damit die Weboberfläche aufgerufen werden kann
metadata:
  name: nextcloud-env # die Verwendete Enviroment Datei
