apiVersion: apps/v1 # Angabe der verwendet Version
kind: Deployment # Gibt an das es sich um eine Deployment Datei handelt
metadata:
  labels: # Dienen als Bennenung fuer die Pods
    service: nextcloud
  name: nextcloud
spec: # Spezifiziert das gewünschte Verhalten des Deployments
  replicas: 1 # Anzahl der laufenden Replicas (Jedes Replica ist eigenstaendig)
  selector:
    matchLabels:
      service: nextcloud
  strategy: # Die Strategie mit der alte Pods durch neue ersetzt werden
    type: Recreate # Falls etwas schief geht wird der Pod anhand der angegebnen Regeln neu erstellt
  template:
    metadata:
      labels:
        service: nextcloud
    spec:
      containers:
        - env: # Gibt an welche Umgebungsvariablen bei Start des Containers gelten. Die Daten stehen in den entsprechenden Enviroment Daten in ../env/
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef: 
                  key: MYSQL_DATABASE
                  name: mariadb-env 
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_HOST
                  name: mariadb-env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: mariadb-env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mariadb-env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: mariadb-env
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              valueFrom:
                configMapKeyRef:
                  key: NEXTCLOUD_TRUSTED_DOMAINS
                  name: nextcloud-env
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: NEXTCLOUD_ADMIN_PASSWORD
                  name: nextcloud-env
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  key: NEXTCLOUD_ADMIN_USER
                  name: nextcloud-env
          image: nextcloud
          name: nextcloud-gcc
          ports:
            - containerPort: 80 # Port des Containers
            - containerPort: 443 # Port des Containers
            # Da Die Nextcloud auf beiden Ports erreichbar sein soll
          resources: 
            limits: # Limit Angabe ueber verfuegbaren Speicher und maximale CPU Zuteilung
              memory: "128Mi" 
              cpu: "500m"
          volumeMounts: # Angabe der zu verwendeten Volumes Pfad und Name
            - mountPath: /var/www/html
              name: nextcloud
      restartPolicy: Always # Falls der Container abstuertzt wird er immer neugestartet, nach hier angegebenen Regeln 
      volumes: # Liste der Volumen, die gemountet werden
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
