apiVersion: v1 # Version der API
kind: PersistentVolumeClaim # Eine Anforderung von Speicherplatz durch einen Benutzer
metadata:
  labels:
    service: nextcloud # Name des Service
  name: nextcloud # Name
spec:
  accessModes:
    - ReadWriteOnce # Kein anderer Pod kann auf das Volume Zugreifen
  resources:
    requests:
      storage: 100Mi # Angabe der Speichergroesse
